version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.8.3
    - 3.9.0
    - 3.9.1
  - dependency-name: open
    versions:
    - 7.3.1
    - 7.4.0
    - 7.4.1
    - 7.4.2
    - 8.0.1
    - 8.0.2
    - 8.0.3
    - 8.0.4
    - 8.0.5
    - 8.0.6
  - dependency-name: eslint
    versions:
    - 4.19.1
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: eslint-plugin-react
    versions:
    - 6.10.3
    - 7.22.0
    - 7.23.0
    - 7.23.1
  - dependency-name: karma
    versions:
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.1.1
    - 6.1.2
    - 6.2.0
    - 6.3.0
    - 6.3.1
  - dependency-name: chai
    versions:
    - 4.2.0
    - 4.3.0
    - 4.3.1
    - 4.3.3
  - dependency-name: jquery
    versions:
    - 3.5.1
  - dependency-name: babel-eslint
    versions:
    - 9.0.0
  - dependency-name: url-loader
    versions:
    - 0.6.2
